name: Java CI
#
on: push

jobs:
  build:
    name : Integration Continue = tests + build + generation rapports AUTO
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'corretto'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        #uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run:  chmod +x ./gradlew
      - name: Build & test and compute JaCoCo reports
        run: ./gradlew build #JacocoTestReport
